### ISSUE TITLE
uninstall plugin

### ISSUE THREAD

**Issue by Rweil1** [mlamoure/Indigo-August-Home#2]
Hello,

I tried installing the new release and errors come up saying the destination file is already there and won't proceed. 

Can you please let me know how to uninstall the plugin and then i could reinstall from scratch.

I deleted the August lock device and have tried stopping the plugin but Im stuck.

Thanks for the help!

**Comment by mlamoure** [comment]
Stop your server, and Go to /Library/Application Support/perceptive automation/Indigo 7/plugins and plugins (disabled).  Remove the plugin and then start your server, install again.  Your preferences will stay.

**Comment by mlamoure** [comment]
You don’t need to delete your lock device

**Comment by mlamoure** [comment]
The api key is also out of date, so you may want to wait until I update the plugin tomorrow

**Comment by Rweil1** [comment]
Thanks for the help!

I will wait until you update.

Rich

**Comment by mlamoure** [comment]
v1.0.14 is now available.

**Comment by Rweil1** [comment]
Thank you for the help! Everything is working great again.

Rich
