### ISSUE TITLE
Can't get a validation code

### ISSUE THREAD

**Issue by dssinger** [mlamoure/Indigo-August-Home#3]
I'm trying to install the plugin in a fresh Indigo installation, but August is rejecting the API key.

Response HTTP Status Code: 403
Response HTTP Response Body: {"code":"ForbiddenError","message":"API key is not valid"}
{'x-response-time': '1', 'Content-Length': '58', 'Server': 'nginx/1.15.2', 'Connection': 'keep-alive', 'Date': 'Fri, 10 Aug 2018 00:34:56 GMT', 'Content-Type': 'application/json'}

Any help would be appreciated.  Thanks!

**Comment by snjoetw** [comment]
Most likely this is due to August API key expired, I've made the change in my repo: https://github.com/snjoetw/py-august/commit/688ed4e3727447109868d4ed848f3bedc99a00db

**Comment by mlamoure** [comment]
Thanks.  Mine started failing too.  I’m traveling and could not debug while away.  I’ll merge this in tomorrow.

**Comment by dssinger** [comment]
I patched my copy of the plugin and all is well.  I'll pick up the official update when you merge it in.  Thanks.

**Comment by mlamoure** [comment]
fixed in v1.0.14, available now.
