### ISSUE TITLE
API Key Not Valid

### ISSUE THREAD

**Issue by wonderslug** [mlamoure/Indigo-August-Home#4]
Howdy

Started setting some errors using the plugin so I debugged it a bit and I am seeing a failure of the API key thats embedded in the script for the rest calls.

I was able to replace it with one I found in another location (https://github.com/jmaxxz/keymaker/issues/5) and it seems to work.

**Comment by wonderslug** [comment]
Closing issue.  Just got beat to it by https://github.com/mlamoure/Indigo-August-Home/issues/3

**Comment by mlamoure** [comment]
Fixed in v1.0.14, available now
