### ISSUE TITLE
verification /login fail

### ISSUE THREAD

**Issue by farberm** [mlamoure/Indigo-August-Home#5]
i am getting the following error when i try to test the login/verification. i tried both my email, and phone number. I have verified that my login and password are correct

    startup called
   August Home Debug               Starting concurrent tread
   August Home Debug               Response HTTP Status Code: 200
   August Home Debug               Response HTTP Response Body: {"installId":"993be63e-9152-4580-82b2-280946851a57","applicationId":"","userId":"15637d49-f79f-4402-af6d-95d3e43bf958","vInstallId":false,"vPassword":false,"vEmail":false,"vPhone":false,"hasInstallId":true,"hasPassword":true,"hasEmail":true,"hasPhone":true,"isLockedOut":false,"captcha":"","email":[],"phone":[],"expiresAt":"2018-12-12T09:46:43.773Z","LastName":"","FirstName":""}
   August Home Error               Login failed

**Comment by mlamoure** [comment]
Are you on the latest release of the plugin?  I updated the API on Friday last week.

**Comment by mlamoure** [comment]
And did you get a confirmation code from August when you tried to login?

**Comment by mlamoure** [comment]
Any update on your issue?

**Comment by farberm** [comment]
Solved
