### ISSUE TITLE
August Lock Pro with Connect

### ISSUE THREAD

**Issue by hassancy** [mlamoure/Indigo-August-Home#6]
I have been able to add all my August Locks which are all connected to August Connects to Indigo.  However, whenever the locks are locked or unlocked I always get a 'received "Garage Door" PIN Code was added or removed for a user (ignored)' message in the log.  Sometimes the plugin manages to receive the change in status in about 30 seconds or so after the first message but sometimes it misses the change in status.  If I request a status update (even if it is from a lock that was not locked or unlocked), the change in status is recognized.  My polling interval is 15 seconds.

**Comment by mlamoure** [comment]
this has been fixed.
