### ISSUE TITLE
Set lock codes?

### ISSUE THREAD

**Issue by wootwoot1234** [mlamoure/Indigo-August-Home#8]
Hello.

I'm interested in using this to set the lock codes on the lock. Is that possible using this library? If not, do you know if it's possible use the API at all?

Thanks!

**Comment by mlamoure** [comment]
No, sorry.  You may want to check the Hombridge implementation libraries.  The open source libraries didn't exist when I built my plugin so I built my own API layer and have not implementated that.

**Comment by wootwoot1234** [comment]
Thank you!
